"""Disclaimer copy appended to user-facing LLM output.

Kept as a single string so we can evolve the legal wording in one place.
"""

DISCLAIMER = (
    "This content was generated by an AI assistant from portfolio data. "
    "It is for informational purposes only and does not constitute "
    "investment advice, a recommendation, or an offer to transact."
)


def with_disclaimer(text: str) -> str:
    """Append the standard disclaimer to a generated string."""
    if not text:
        return text
    return f"{text.rstrip()}\n\n— {DISCLAIMER}"
