"use client";

import { ReactNode } from "react";
import { Markdown } from "./Markdown";
import { SourceDataPanel } from "./SourceDataPanel";

/** Canonical disclaimer shown on every agent surface (matches the backend copy). */
export const AGENT_DISCLAIMER =
  "AI-generated from your portfolio data — for informational purposes only; " +
  "not investment advice, a recommendation, or an offer to transact.";

/** Backends append "— This content was generated by an AI…" into the text; strip it
 *  so the shell can render the disclaimer once, consistently, in the footer. */
export function stripDisclaimer(text: string): string {
  return text.replace(/\n+—\s*This content was generated by an AI[\s\S]*$/i, "").trimEnd();
}

type Props = {
  title: string;
  subtitle?: string;
  onRun: () => void;
  isPending: boolean;
  runLabel?: string; // verb for the first run, e.g. "Generate" | "Explain"
  disabled?: boolean;
  markdown?: string | null; // free-text agent output → rendered as markdown
  children?: ReactNode; // structured content (rendered after the markdown body)
  error?: string | null;
  sourceData?: unknown;
  cached?: boolean | null;
  model?: string | null;
  className?: string;
};

export function AgentCard({
  title, subtitle, onRun, isPending, runLabel = "Generate", disabled,
  markdown, children, error, sourceData, cached, model, className = "",
}: Props) {
  const body = markdown ? stripDisclaimer(markdown) : "";
  const hasResult = !!(body || children);

  const copy = () => {
    if (body) navigator.clipboard?.writeText(body);
  };

  return (
    <div className={`q-card p-5 ${className}`}>
      <div className="mb-3 flex items-start justify-between gap-3">
        <div>
          <div className="flex items-center gap-2">
            <h2 className="text-sm font-semibold text-[var(--text-primary)]">{title}</h2>
            <span className="rounded-full bg-[var(--teal-light)] px-1.5 py-0.5 text-[9px] font-semibold uppercase tracking-wide text-[var(--teal-muted)]">
              AI
            </span>
          </div>
          {subtitle && <p className="text-xs text-[var(--text-muted)]">{subtitle}</p>}
        </div>
        <div className="flex items-center gap-2">
          {body && (
            <button
              onClick={copy}
              className="text-[11px] font-medium text-[var(--text-secondary)] hover:text-[var(--navy)]"
            >
              Copy
            </button>
          )}
          <button
            onClick={onRun}
            disabled={disabled || isPending}
            className="rounded-lg bg-[var(--navy)] px-3 py-1.5 text-xs font-medium text-white hover:opacity-90 disabled:opacity-50"
          >
            {isPending ? "Generating…" : hasResult ? "Regenerate" : runLabel}
          </button>
        </div>
      </div>

      {isPending && (
        <div className="space-y-2">
          <div className="h-3 w-2/3 animate-pulse rounded bg-[var(--card-border)]" />
          <div className="h-3 w-full animate-pulse rounded bg-[var(--card-border)]" />
          <div className="h-3 w-5/6 animate-pulse rounded bg-[var(--card-border)]" />
        </div>
      )}

      {error && !isPending && (
        <div className="rounded bg-[var(--coral-light)] px-3 py-2 text-xs text-[var(--coral)]">{error}</div>
      )}

      {hasResult && !isPending && (
        <div className="space-y-3">
          {body && <Markdown>{body}</Markdown>}
          {children}
          {sourceData != null && <SourceDataPanel data={sourceData} />}
          <p className="text-[10px] text-[var(--text-muted)]">
            {cached ? "Cached · " : ""}
            {model ? `${model} · ` : ""}
            {AGENT_DISCLAIMER}
          </p>
        </div>
      )}
    </div>
  );
}
